// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFESVS7QTDSloi2OsFZpk8hTDgPXhoQ28',
    appId: '1:922971863459:web:996de5e7ea02fdf7230216',
    messagingSenderId: '922971863459',
    projectId: 'peps-inv',
    authDomain: 'peps-inv.firebaseapp.com',
    storageBucket: 'peps-inv.firebasestorage.app',
    measurementId: 'G-8PC1JPW5KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1fmujl-esJoetoA5fjKesIQgSD8nYDo',
    appId: '1:922971863459:android:1e463e9d76d8aa85230216',
    messagingSenderId: '922971863459',
    projectId: 'peps-inv',
    storageBucket: 'peps-inv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuaGmiMyMlMRS_teAKPWttHx2H-0WOsBw',
    appId: '1:922971863459:ios:20c8cc95e8e5a07e230216',
    messagingSenderId: '922971863459',
    projectId: 'peps-inv',
    storageBucket: 'peps-inv.firebasestorage.app',
    iosBundleId: 'com.example.inventarioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuaGmiMyMlMRS_teAKPWttHx2H-0WOsBw',
    appId: '1:922971863459:ios:20c8cc95e8e5a07e230216',
    messagingSenderId: '922971863459',
    projectId: 'peps-inv',
    storageBucket: 'peps-inv.firebasestorage.app',
    iosBundleId: 'com.example.inventarioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFESVS7QTDSloi2OsFZpk8hTDgPXhoQ28',
    appId: '1:922971863459:web:fefae78ca99e9645230216',
    messagingSenderId: '922971863459',
    projectId: 'peps-inv',
    authDomain: 'peps-inv.firebaseapp.com',
    storageBucket: 'peps-inv.firebasestorage.app',
    measurementId: 'G-HPZC6P96EN',
  );
}
